const data = [
    {
        licensePlate: 'SG89410',
        name: 'Lottie Mack',
        location: '105 Hied Lane, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Mae Frank Transport Pte. Ltd.',
        lat: 1.313430, lng: 103.869679
    },
    {
        licensePlate: 'SG95725',
        name: 'Jorge Chapman',
        location: '5 Ojca Point, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Irene Hampton Transport Pte. Ltd.',
        lat: 1.302534, lng: 103.874961
    },
    {
        licensePlate: 'SG85053',
        name: 'Alvin Jackson',
        location: '972 Woiku Center, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Tommy Perry Transport Pte. Ltd.',
        lat: 1.310626, lng: 103.791417
    },
    {
        licensePlate: 'SG16581',
        name: 'Clifford Sanchez',
        location: '133 Enju Trail, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Miguel Moody Transport Pte. Ltd.',
        lat: 1.324518, lng: 103.884048
    },
    {
        licensePlate: 'SG70075',
        name: 'Rachel Underwood',
        location: '115 Zape Heights, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Terry Burton Transport Pte. Ltd.',
        lat: 1.325966, lng: 103.897489
    },
    {
        licensePlate: 'SG97822',
        name: 'Brett George',
        location: '315 Abise Trail, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Chase Schneider Transport Pte. Ltd.',
        lat: 1.350622, lng: 103.686349
    },
    {
        licensePlate: 'SG74997',
        name: 'Norman Holmes',
        location: '1410 Effim Mill, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Lucinda Burgess Transport Pte. Ltd.',
        lat: 1.374361, lng: 103.732754
    },
    {
        licensePlate: 'SG59896',
        name: 'Mathilda Pratt',
        location: '1687 Feki Turnpike, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Bryan Cooper Transport Pte. Ltd.',
        lat: 1.302683, lng: 103.889547
    },
    {
        licensePlate: 'SG59339',
        name: 'Mason Dunn',
        location: '508 Losaz Terrace, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Mildred Watkins Transport Pte. Ltd.',
        lat: 1.302506, lng: 103.824569
    },
    {
        licensePlate: 'SG40015',
        name: 'Lucille Jimenez',
        location: '934 Bizji River, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Alexander Owen Transport Pte. Ltd.',
        lat: 1.298877, lng: 103.797569
    },
    {
        licensePlate: 'SG28489',
        name: 'Lida Soto',
        location: '418 Fihuk Junction, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Richard Lane Transport Pte. Ltd.',
        lat: 1.3068166, lng: 103.742364
    },
    {
        licensePlate: 'SG98309',
        name: 'Francisco Ortega',
        location: '1271 Fuvaj Pass, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Cole Shaw Transport Pte. Ltd.',
        lat: 1.3160362, lng: 103.892915
    },
    {
        licensePlate: 'SG78323',
        name: 'Leah Tyler',
        location: '969 Jewka Avenue, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Chad Mathis Transport Pte. Ltd.',
        lat: 1.4313875, lng: 103.807748
    },
    {
        licensePlate: 'SG65182',
        name: 'Devin Salazar',
        location: '1420 Hijur Street, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Louisa Porter Transport Pte. Ltd.',
        lat: 1.3455674, lng: 103.735188
    },
    {
        licensePlate: 'SG89655',
        name: 'Alex Neal',
        location: '1805 Akdow Place, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Iva Morales Transport Pte. Ltd.',
        lat: 1.3336415, lng: 103.700681
    },
    {
        licensePlate: 'SG94403',
        name: 'Philip Allen',
        location: '1468 Bohok Way, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Leon Bowman Transport Pte. Ltd.',
        lat: 1.3005089, lng: 103.846152
    },
    {
        licensePlate: 'SG67721',
        name: 'Christopher Sullivan',
        location: '858 Samed Street, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Ivan Stevenson Transport Pte. Ltd.',
        lat: 1.3910480, lng: 103.858098
    },
    {
        licensePlate: 'SG36421',
        name: 'Carlos Steele',
        location: '964 Niena Center, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Keith Miles Transport Pte. Ltd.',
        lat: 1.3548947, lng: 103.738656
    },
    {
        licensePlate: 'SG25422',
        name: 'Christina Freeman',
        location: '528 Zasmu Terrace, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Inez Simon Transport Pte. Ltd.',
        lat: 1.322861, lng: 103.853694
    },
    {
        licensePlate: 'SG41064',
        name: 'Caleb Alvarado',
        location: '1777 Savte Junction, Singapore',
        status: 'Moving',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Eliza Harrison Transport Pte. Ltd.',
        lat: 1.346226, lng: 103.868213
    },
    {
        licensePlate: 'SG76270',
        name: 'Jeff Duncan',
        location: '31 Sione Mill, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Ryan Diaz Transport Pte. Ltd.',
        lat: 1.3860635, lng: 103.868559
    },
    {
        licensePlate: 'SG20375',
        name: 'Harriett Murray',
        location: '287 Fatuf Plaza, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Lettie Thompson Transport Pte. Ltd.',
        lat: 1.2815734, lng: 103.857230
    },
    {
        licensePlate: 'SG74919',
        name: 'Darrell Conner',
        location: '1044 Bagbe Lane, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Walter Ferguson Transport Pte. Ltd.',
        lat: 1.3630860, lng: 103.713559
    },
    {
        licensePlate: 'SG51891',
        name: 'Sam McKinney',
        location: '115 Afve Avenue, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Jordan Barrett Transport Pte. Ltd.',
        lat: 1.364361, lng: 103.732754
    },
    {
        licensePlate: 'SG45342',
        name: 'Hulda Harrington',
        location: '159 Delsi Turnpike, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Jacob Bennett Transport Pte. Ltd.',
        lat: 1.354361, lng: 103.732754
    },
    {
        licensePlate: 'SG19287',
        name: 'Allen Adkins',
        location: '1983 Tego Path, Singapore',
        status: 'Out of Region',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Leila Yates Transport Pte. Ltd.',
        lat: 1.4376449, lng: 103.707802
    },
    {
        licensePlate: 'SG21798',
        name: 'Myrtle Howell',
        location: '1542 Seza Plaza, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Sophie Floyd Transport Pte. Ltd.',
        lat: 1.3229237, lng: 103.899646
    },
    {
        licensePlate: 'SG14726',
        name: 'Francis Butler',
        location: '349 Beflo Center, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Brian Fowler Transport Pte. Ltd.',
        lat: 1.398968, lng: 103.737249
    },
    {
        licensePlate: 'SG58878',
        name: 'Elva Kim',
        location: '1567 Feir Street, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Dora Nelson Transport Pte. Ltd.',
        lat: 1.325436, lng: 103.795160
    },
    {
        licensePlate: 'SG60006',
        name: 'Floyd King',
        location: '418 Hepi Junction, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Linnie Summers Transport Pte. Ltd.',
        lat: 1.317714, lng: 103.721052
    },
    {
        licensePlate: 'SG76927',
        name: 'Russell Harmon',
        location: '1294 Gapuw River, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Marie Schultz Transport Pte. Ltd.',
        lat: 1.375794, lng: 103.860777
    },
    {
        licensePlate: 'SG10847',
        name: 'Lucille Johnston',
        location: '697 Lecjok Pass, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Bruce Townsend Transport Pte. Ltd.',
        lat: 1.355671, lng: 103.871877
    },
  
    {
        licensePlate: 'SG44437',
        name: 'Jennie Ortiz',
        location: '106 Wuzil Drive, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Marie Riley Transport Pte. Ltd.',
        lat: 1.386489, lng: 103.712845
    },
    {
        licensePlate: 'SG95825',
        name: 'Allie Moreno',
        location: '70 Ficsu Plaza, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Mason Marsh Transport Pte. Ltd.',
        lat: 1.322269, lng: 103.860863
    },
    {
        licensePlate: 'SG40757',
        name: 'Mittie Davis',
        location: '609 Donfo Pike, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Jerry Lowe Transport Pte. Ltd.',
        lat: 1.366703, lng: 103.728414
    },
    {
        licensePlate: 'SG33239',
        name: 'Albert Santos',
        location: '1209 Zifav Pike, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Margaret Roberts Transport Pte. Ltd.',
        lat: 1.391645, lng: 103.770522
    },
    {
        licensePlate: 'SG20886',
        name: 'Isaiah Lawson',
        location: '1295 Dumzus Boulevard, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Abbie Schneider Transport Pte. Ltd.',
        lat: 1.366333, lng: 103.732612
    },
    {
        licensePlate: 'SG60241',
        name: 'Wayne Harper',
        location: '25 Kidu River, Singapore',
        status: 'Offline',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Birdie Roy Transport Pte. Ltd.',
        lat: 1.355315, lng: 103.784720
    },
    {
        licensePlate: 'SG98388',
        name: 'Chester Cook',
        location: '1943 Ihupa Extension, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Margaret Santiago Transport Pte. Ltd.',
        lat: 1.376935, lng: 103.840801
    },
    {
        licensePlate: 'SG76064',
        name: 'Roy Adkins',
        location: '1360 Kekpi Point, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Dean Young Transport Pte. Ltd.',
        lat: 1.354612, lng: 103.673083
    },
    {
        licensePlate: 'SG88893',
        name: 'Marie Owens',
        location: '595 Ciffa Key, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Corey Santiago Transport Pte. Ltd.',
        lat: 1.304568, lng: 103.771752
    },
    {
        licensePlate: 'SG74781',
        name: 'Cody Newman',
        location: '642 Neja Mill, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Aaron Myers Transport Pte. Ltd.',
        lat: 1.309902, lng: 103.827091
    },
    {
        licensePlate: 'SG35653',
        name: 'Beulah Franklin',
        location: '12 Zovez Heights, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Jordan Hampton Transport Pte. Ltd.',
        lat: 1.387127, lng: 103.880772
    },
    {
        licensePlate: 'SG60490',
        name: 'Mathilda Strickland',
        location: '1138 Minru Lane, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Della Frank Transport Pte. Ltd.',
        lat: 1.366639, lng: 103.749898
    },
    {
        licensePlate: 'SG41406',
        name: 'Jesse Sherman',
        location: '1552 Catlih Center, Singapore',
        status: 'Parked',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Sam Coleman Transport Pte. Ltd.',
        lat: 1.347402, lng: 103.673379
    },
    {
        licensePlate: 'SG10385',
        name: 'Russell Harris',
        location: '215 Ulkom Lane, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Sara Thornton Transport Pte. Ltd.',
        lat: 1.358156, lng: 103.716435
    },
    {
        licensePlate: 'SG19422',
        name: 'Alice Rose',
        location: '1664 Ispug Way, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Nicholas Hunt Transport Pte. Ltd.',
        lat: 1.313745, lng: 103.837285
    },
    {
        licensePlate: 'SG84315',
        name: 'Lula Fox',
        location: '760 Hojuf Lane, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Dale Flores Transport Pte. Ltd.',
        lat: 1.365772, lng: 103.772341
    },
    {
        licensePlate: 'SG33075',
        name: 'Estelle Murphy',
        location: '978 Emeej Point, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Wayne Parker Transport Pte. Ltd.',
        lat: 1.308266, lng: 103.685788
    },
    {
        licensePlate: 'SG47293',
        name: 'Jonathan McGuire',
        location: '48 Pozi Heights, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Raymond Johnston Transport Pte. Ltd.',
        lat: 1.344004, lng: 103.727533
    },
    {
        licensePlate: 'SG93869',
        name: 'Lily Owens',
        location: '279 Jica Lane, Singapore',
        status: 'Idling',
        statusDetail: 'ACC off, unlocated, circuit runs well, door is unlocked, oil circuit is normal.',
        time: '22/05/2017, 13:31:49 PM',
        speed: '24 km/h',
        direction: 'north by east',
        place: 'Rhoda Bass Transport Pte. Ltd.',
        lat: 1.397599, lng: 103.766923
    },
];

export default data;
